### ISSUE TITLE
BUG | 1.20.1下骑乘飞船无法打开面板

### ISSUE THREAD

**Issue by Fangtang3** [Wenkrangha/BoatFly#2]
## 你在哪方面遇到了问题
在骑乘飞船时遇到问题
## 期望结果
控制台不显示报错按下左Shift正常打开控制面板
## 实际结果
骑乘时会在控制台返回错误，无法正常打开面板
## 服务端信息
``` Console
This server is running Plazma version git-Plazma-"b4a9581" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b4a9581 on ver/1.20.1)
```
## 报错
```Console
[10:08:12] [Server thread/ERROR]: Could not pass event VehicleEnterEvent to BoatFly v1.0-SNAPSHOT
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
	at com.wenkrang.boatfly.event.VehicleEnter.OnVehicleEnterEvent(VehicleEnter.java:18) ~[BoatFly-1.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:40) ~[plazma-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[plazma-api-1.20.1-R0.1-SNAPSHOT.jar:git-Plazma-"b4a9581"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[plazma-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:62) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[plazma-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.Entity.startRiding(Entity.java:2890) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.server.level.ServerPlayer.startRiding(ServerPlayer.java:2647) ~[?:?]
	at net.minecraft.world.entity.Entity.startRiding(Entity.java:2863) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.world.entity.vehicle.Boat.interact(Boat.java:901) ~[?:?]
	at net.minecraft.world.entity.player.Player.interactOn(Player.java:1168) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.performInteraction(ServerGamePacketListenerImpl.java:2982) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:3002) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2941) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1367) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1344) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1337) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[plazma-1.20.1.jar:git-Plazma-"b4a9581"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
## 说明
经测试，1.20.2及以上版本不会出现此Bug

**Comment by Fangtang3** [comment]
fixed in 1.0

**Comment by Wenkrangha** [comment]
问题已修复，并且加强了稳定性,发现潜在问题

**Comment by Fangtang3** [comment]
又不能用了？

**Comment by Wenkrangha** [comment]
其他的服务端应该可以用了

**Comment by Wenkrangha** [comment]
我准备发布1.2版本
