### ISSUE TITLE
能不能设置一个取消在线更新的选项

### ISSUE THREAD

**Issue by znc15** [Wenkrangha/BoatFly#25]
能不能设置一个取消在线更新的选项，不然开启的时候，无法连接就报错（
```
[16:44:25 WARN]: [BoatFly] Plugin BoatFly v${project.version} generated an exception while executing task 236
java.lang.RuntimeException: java.net.ConnectException: Connection refused
        at com.wenkrang.boatfly.UpgradeSystem.UpgradeCheck$1.run(UpgradeCheck.java:29) ~[BoatFly-1.5.5b.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2034]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.1.jar:git-Purpur-2034]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.net.ConnectException: Connection refused
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:639) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:533) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:638) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1245) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1131) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1668) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at com.wenkrang.boatfly.lib.UnsafeDownloader.downloadFile(UnsafeDownloader.java:24) ~[BoatFly-1.5.5b.jar:?]
        at com.wenkrang.boatfly.UpgradeSystem.Source.getSource(Source.java:20) ~[BoatFly-1.5.5b.jar:?]
        at com.wenkrang.boatfly.UpgradeSystem.UpgradeCheck$1.run(UpgradeCheck.java:26) ~[BoatFly-1.5.5b.jar:?]
        ... 6 more
```

**Comment by Wenkrangha** [comment]
可以

**Comment by Wenkrangha** [comment]
好了，我修复了国内无法访问的问题，我把更新源该到了gitee
