### ISSUE TITLE
BUG | isVersionBelow处理带多个小数点的版本时遇到问题

### ISSUE THREAD

**Issue by Fangtang3** [Wenkrangha/BoatFly#30]
在启动插件时遇到此问题，导致插件无法正常启动
## 服务端信息
``` Console
This server is running Leaf version 1.20.6-DEV-ver/1.20.6@f0e36a8 (2024-07-04T12:39:59Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
```
## 报错
``` Console
[06:54:16 ERROR]: Error occurred while enabling BoatFly v${project.version} (Is it up to date?)
java.lang.NumberFormatException: multiple points
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:?]
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source) ~[?:?]
        at java.base/java.lang.Float.parseFloat(Unknown Source) ~[?:?]
        at BoatFly-1.5.5c-1722552852422.jar/com.wenkrang.boatfly.lib.VersionChecker.isVersionBelow(VersionChecker.java:30) ~[BoatFly-1.5.5c-1722552852422.jar:?]
        at BoatFly-1.5.5c-1722552852422.jar/com.wenkrang.boatfly.BoatFly.onEnable(BoatFly.java:19) ~[BoatFly-1.5.5c-1722552852422.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at BoatFly-BootLoader-1.5.5c.jar/com.wenkrang.boatflybootloader.BoatFly_BootLoader.onEnable(BoatFly_BootLoader.java:34) ~[BoatFly-BootLoader-1.5.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:648) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:597) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:367) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1145) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```
## 说明
理论上任何带两个小数点的mc版本都会造导致这个问题

**Comment by Fangtang3** [comment]
这个问题导致插件直接关闭
``` Console
[06:54:11 INFO]: [BoatFly-BootLoader] Enabling BoatFly-BootLoader v${project.version}
[06:54:12 INFO]: [*] ./plugins/BoatFly/version/BoatFly-1.5.5c.jar
[06:54:12 INFO]: [PluginRemapper] Remapping plugin '.\plugins\BoatFly\version\BoatFly-1.5.5c.jar'...
[06:54:16 INFO]: [PluginRemapper] Done remapping plugin '.\plugins\BoatFly\version\BoatFly-1.5.5c.jar' in 4111ms.
[06:54:16 INFO]: [BoatFly] Loading server plugin BoatFly v${project.version}
[06:54:16 INFO]: [*] BoatFly v${project.version}
[06:54:16 INFO]: [BoatFly] Enabling BoatFly v${project.version}
[06:54:16 ERROR]: Error occurred while enabling BoatFly v${project.version} (Is it up to date?)
java.lang.NumberFormatException: multiple points
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:?]
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source) ~[?:?]
        at java.base/java.lang.Float.parseFloat(Unknown Source) ~[?:?]
        at BoatFly-1.5.5c-1722552852422.jar/com.wenkrang.boatfly.lib.VersionChecker.isVersionBelow(VersionChecker.java:30) ~[BoatFly-1.5.5c-1722552852422.jar:?]
        at BoatFly-1.5.5c-1722552852422.jar/com.wenkrang.boatfly.BoatFly.onEnable(BoatFly.java:19) ~[BoatFly-1.5.5c-1722552852422.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at BoatFly-BootLoader-1.5.5c.jar/com.wenkrang.boatflybootloader.BoatFly_BootLoader.onEnable(BoatFly_BootLoader.java:34) ~[BoatFly-BootLoader-1.5.5c.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:648) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:597) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:367) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1145) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaf-1.20.6.jar:1.20.6-DEV-f0e36a8]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[06:54:16 INFO]: [BoatFly] Disabling BoatFly v${project.version}
[06:54:16 INFO]: [*] 正在关闭 BoatFly ...
```

**Comment by Wenkrangha** [comment]
是个严重的问题

**Comment by xcyawa** [comment]
群里说不行吗（恼
